# Generated by Django 2.2.2 on 2021-11-17 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名前')),
                ('age', models.IntegerField(choices=[(10, '10代'), (20, '20代'), (30, '30代'), (40, '40代'), (50, '50代'), (60, '60代'), (70, '70代'), (80, '80代'), (90, '90代')], verbose_name='年代')),
                ('sex', models.CharField(choices=[('man', '男性'), ('female', '男性')], max_length=40, verbose_name='性別')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Userinfo',
            },
        ),
    ]
