# Generated by Django 2.2.2 on 2021-11-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('man', '男性'), ('female', '女性')], max_length=40, verbose_name='性別'),
        ),
    ]
