# Generated by Django 2.2.2 on 2021-11-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211119_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('男性', '男性'), ('女性', '女性')], max_length=40, null=True, verbose_name='性別'),
        ),
    ]
