# Generated by Django 2.2.2 on 2021-12-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211124_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shokai',
            field=models.TextField(blank=True, null=True, verbose_name='紹介'),
        ),
    ]
