# Generated by Django 2.2.2 on 2022-01-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220114_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, choices=[(10, '10代'), (20, '20代'), (30, '30代'), (40, '40代'), (50, '50代'), (60, '60代'), (70, '70代'), (80, '80代'), (90, '90代'), (100, '100以上')], null=True, verbose_name='年代'),
        ),
    ]
