# Generated by Django 2.2.2 on 2022-01-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220114_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='likerecieve',
            field=models.IntegerField(blank=True, null=True, verbose_name='いいね数'),
        ),
    ]
