# Generated by Django 2.2.2 on 2022-01-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customuser_likerecieve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='likerecieve',
            field=models.IntegerField(default=0, verbose_name='いいね数'),
        ),
    ]
