# Generated by Django 2.2.2 on 2021-11-30 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taro', '0002_auto_20211125_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='taro',
            name='like',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
