# Generated by Django 2.2.2 on 2021-11-30 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taro', '0003_taro_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taro',
            name='like',
        ),
        migrations.AddField(
            model_name='taro',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
