# Generated by Django 2.2.2 on 2021-12-01 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taro', '0004_auto_20211130_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taro',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
