# Generated by Django 2.2.2 on 2022-01-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taro', '0007_auto_20220112_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taro',
            name='kenmei',
            field=models.CharField(blank=True, choices=[('chiba', '千葉'), ('kanagawa', '神奈川'), ('tokyo', '東京'), ('oosaka', '大阪')], max_length=40, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='taro',
            name='okane',
            field=models.IntegerField(blank=True, null=True, verbose_name='料金'),
        ),
    ]
