# Generated by Django 2.2.2 on 2022-01-17 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taro', '0008_auto_20220112_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagname',
            field=models.CharField(max_length=40, verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='taro',
            name='okane',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='料金'),
        ),
    ]
