# Generated by Django 2.2.2 on 2022-01-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taro', '0009_auto_20220117_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taro',
            name='kenmei',
            field=models.CharField(blank=True, choices=[('千葉', 'chiba'), ('kanagawa', '神奈川'), ('tokyo', '東京'), ('oosaka', '大阪')], max_length=40, null=True, verbose_name='都道府県'),
        ),
    ]
