# Generated by Django 2.2.2 on 2022-01-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taro', '0010_auto_20220124_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taro',
            name='kenmei',
            field=models.CharField(blank=True, choices=[('千葉', '千葉'), ('神奈川', '神奈川'), ('東京', '東京'), ('大阪', '大阪')], max_length=40, null=True, verbose_name='都道府県'),
        ),
    ]
