# Generated by Django 2.2.2 on 2022-01-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taro', '0011_auto_20220124_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='taro',
            name='likestotal',
            field=models.IntegerField(default=0, verbose_name='postいいね数'),
        ),
    ]
