# Generated by Django 2.2.2 on 2022-01-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taro', '0012_taro_likestotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taro',
            name='kenmei',
            field=models.CharField(blank=True, choices=[('千葉県', '千葉県'), ('神奈川県', '神奈川県'), ('東京県', '東京県'), ('大阪県', '大阪県')], max_length=40, null=True, verbose_name='都道府県'),
        ),
    ]
